services:
  postgres:
    image: postgres:16
    container_name: aws-orders-postgres
    environment:
      POSTGRES_DB: aws_orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:3.0.2
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3,sqs
      AWS_DEFAULT_REGION: us-east-1
      DEBUG: "1"
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - ./localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data: