spring.application.name=was-order-ingestion-service

# Server port
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/aws_orders
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true